# Site settings
title: UXShot
email: hello@looramoora.com
description: > # this means to ignore newlines until "baseurl:"
  UXShot is a collection of best UX strategies captured in shot
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uxshot.com"
twitter_username: looramoora


# Outputting
permalink: /:categories/:title
timezone: Europe/Rome

# Build settings
markdown: kramdown

paginate: 2
# paginate_path: "/page:num/"
